### ISSUE TITLE
Avoid cutting pointcloud

### ISSUE THREAD

**Issue by jdgalviss** [KIT-ISAS/lili-om#34]
I am using lili-om-rot with an ouster 0 lidar (64 lines, 512 points). When I run run.launch this is what I get:
![image](https://user-images.githubusercontent.com/18732666/120651447-d8b46300-c48f-11eb-995a-cab78325af44.png)
As you can tell, the pointcloud is reduced to just a few lines after being preprocessed. I was wondering if this is normal behavior because it actually seems to be performing SLAM correctly on these few lines. Is there is any parameter or part of the code I can change so that the map is built on the full point cloud (64 lines). This is my config file:
```
common:
  frame_id: "lili_om_rot"
  data_set: "iosb"
  
IMU:
  acc_n: 2000
  gyr_n: 0.0173
  acc_w: 2
  gyr_w: 0.00025

preprocessing:
  lidar_topic: "/os_cloud_node/points"
  ds_rate: 2
  line_num: 64
  cut_pointcloud: true

lidar_odometry:
  max_num_iter: 12
  scan_match_cnt: 1
  if_to_deskew: false

backend_fusion:
  max_num_iter: 15
  loop_closure_on: true
  local_map_width: 50
  lc_search_radius: 15
  lc_map_width: 25
  lc_icp_thres: 0.2
  slide_window_width: 3
  imu_topic: "/imu/data"
  lidar_const: 7.5
  mapping_interval: 10
  lc_time_thres: 60.0
  surf_dist_thres: 0.12
  kd_max_radius: 1.0
  save_pcd: false

#extrinsic imu to lidar
  ql2b_w: 1.0
  ql2b_x: 0
  ql2b_y: 0
  ql2b_z: 0.0

  tl2b_x: 0.0
  tl2b_y: 0
  tl2b_z: 0.3
```

Thank you.
